1.Python program to add two Matrices

In [19]:
a=[[1,2,3],
   [4,5,6], 
   [7,8,9]]

b=[[1,2,3],
   [4,5,6], 
   [7,8,9]]

result=[[0,0,0],
       [0,0,0], 
       [0,0,0]]
for i in range(len(a)):
    for j in range(len(a[0])):
        result[i][j]=a[i][j]+b[i][j]
for r in result:
    print(r)


[2, 4, 6]
[8, 10, 12]
[14, 16, 18]


2.Python program to multiply two matrices

In [37]:
a=[[1,2,3],
  [4,5,6], 
  [7,8,9]]

b=[[1,2,3],
   [4,5,6], 
   [7,8,9]]

result=[[0,0,0],
       [0,0,0], 
       [0,0,0]]
for i in range(len(a)):
    for j in range(len(a[0])):
        result[i][j]=a[i][j]*b[i][j]
for r in result:
    print(r)

[1, 4, 9]
[16, 25, 36]
[49, 64, 81]


3.Python program for Matrix Product

In [7]:
'using numpy lib'
import numpy as np 

A = [[12, 7, 3], [4, 5, 6], [7, 8, 9]]
B = [[5, 8, 1, 2], [6, 7, 3, 0], [4, 5, 9, 1]]

result= [[0,0,0,0], [0,0,0,0], [0,0,0,0]]
result= np.dot(A,B)

for p in result:
    print(p)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


4.Adding and Subtracting Matrices in Python

In [19]:
a=[[5,63,2],
   [6,9,8],
   [5,3,6]]
b=[[8,6,9],
   [7,4,8],
   [22,6,3]]
c=[[0,0,0],
   [0,0,0],
   [0,0,0]]
for i in range(len(a)):
    for j in range(len(a[0])):
        c[i][j]=a[i][j]+b[i][j]
print("addition of matrices is")
for k in c:
    print(k)
    
for i in range(len(a)):
    for j in range(len(a[0])):
        c[i][j]=a[i][j]-b[i][j]
print("subtraction of matrices is")
for k in c:
    print(k)


addition of matrices is
[13, 69, 11]
[13, 13, 16]
[27, 9, 9]
subtraction of matrices is
[-3, 57, -7]
[-1, 5, 0]
[-17, -3, 3]


5.Transpose a matrix in Single line in Python

In [6]:
'Using numpy'
import numpy as np
m = [[1,2],[3,4],[5,6]]
n=np.transpose(m)
print(n)

[[1 3 5]
 [2 4 6]]


6.Python | Matrix creation of n*n

In [6]:
n=4

m=[list(range(1+n*i,1+n*(i+1))) for i in range(n)]
print(m)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


7.Python | Get Kth Column of Matrix

In [7]:
m = [[1,2],[3,4],[5,6]]
k=1
n=[i[k] for i in m]
print(n)

[2, 4, 6]


8.Python – Vertical Concatenation in Matrix

In [12]:
test_list = [["Gfg", "good"], ["is", "for"], ["Best"]]
  
print("The original list : " + str(test_list))
  
res = []
N = 0
while N != len(test_list):
    temp = ''
    for idx in test_list:
        try: temp = temp + idx[N]
        except IndexError: pass
    res.append(temp)
    N = N + 1
    res = [ele for ele in res if ele]
   
print("List after column Concatenation : " + str(res))

The original list : [['Gfg', 'good'], ['is', 'for'], ['Best']]
List after column Concatenation : ['GfgisBest', 'goodfor']


9.Python program to check if a string is palindrome or not

In [30]:
"1st sloution"

s="radar"

a=""

for i in s:
    a=i+a
if s==a:
    print(True)
else:
    print(False)

True


In [31]:
"2nd solution"

s="saurabh"

a=s[::-1]

if s==a:
    print(True)
else:
    print(False)

False


10.Python program to check whether the string is Symmetrical or Palindrome

In [83]:
s="tintin"
h=[]
p=[]

a=s[::-1]

b=int((len(s)/2))

if s==a:
    print("It's palindrome ")

else:
    print("No palindrome")

for k in range(b):
    c=s[k]
    h.append(c)
    
for o in range(b,len(s)):
    l=s[o]
    p.append(l)
    
if h==p:
    print("It's symmetrical")
else:
    print("No symmetrical")

No palindrome
It's symmetrical
